__title__ = 'wiki_nodes'
__description__ = 'Wiki Nodes'
__url__ = 'https://github.com/dskrypa/wiki_nodes'
__version__ = '2025.10.19-1'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__copyright__ = 'Copyright 2025 Doug Skrypa'
